### ISSUE TITLE
Not an issue :p

### ISSUE THREAD

**Issue by NateBrune** [Widdershin/helix-pi#34]
Hey man this is a cool cool project and I liked your video on the home page.
The reason I made this issue is to draw your attention to my project for maybe some inspiration on how to handle things. Namely how I handle evolution.

https://github.com/NateBrune/Skynet-Experiments

I don't know man just thought I might help a little :)
If you have any questions just ask em

**Comment by Widdershin** [comment]
That's a cool project. Do you implement breeding? It looks like you replace the 7 losing brains with the winning brain and then mutate it.

Have you considered having a larger population size and then breeding them together based on their fitness?

With that approach, I get pretty good results with Helix Pi within a few hundred generations or so.
